### ISSUE TITLE
An error message of sensitive.tfvars

### ISSUE THREAD

**Issue by duanvnc** [LukeMwila/aws-apigateway-vpc-ecs-fargate#4]
I got an error message when run `terragrunt plan`
```
Error: Failed to read variables file

Given variables file
aws-apigateway-vpc-ecs-fargate/sensitive.tfvars
does not exist.

[terragrunt] 2020/11/02 14:41:04 Hit multiple errors:
```

How can fix it?

**Comment by LukeMwila** [comment]
Hi @duanvnc , you have to create a file called sensitive.tfvars to populate the values for the variables that you would consider sensitive.
For example:
account_id = your AWS account ID
profile = "your-iam-profile" # configured with aws cli
region  = "eu-west-1"
availability_zones = ["eu-west-1a", "eu-west-1b"]
github_secret_name = "githubSecretName" # Only relevant if you're sourcing a GitHub repository.
platform_name = "name-of-your-platform"
app_port = 8080 # This approach would change if you're running multiple containers in ECS. You could perhaps use a map.
app_image = docker image uri

**Comment by httcdev** [comment]
@LukeMwila Thank you so much, it has been resolved. However, I got another error to set main_pvt_route_table_id, is it able to auto-creates the route table instead of creating main_pvt_route_table_id manually?

**Comment by duanvnc** [comment]
@LukeMwila Thank you so much, it has been resolved. However, I got another error to set main_pvt_route_table_id, is it able to auto-creates the route table instead of creating main_pvt_route_table_id manually?

**Comment by duanvnc** [comment]
@LukeMwila Can you help with that issue? because always got an error for main_route_table, after I copy the main route table id of VPC which one created, then replace to vars to run again, it will bypass that case.

**Comment by LukeMwila** [comment]
Hey @duanvnc , sorry for the late response. You can use the default_route_table_id property from your vpc. It's a much better approach, I just hadn't updated my source code. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_route_table

**Comment by duanvnc** [comment]
@LukeMwila Thank you so much!
